openapi: 3.0.2
servers:
  - url: https://telepieza.com/recambios
    description:  [Telepieza Recambios](https://telepieza.com/recambios) Production server using Opencart.
    
  - url: https://recambioslim.com/recambios
    description: My localhost server using PHP built-in web server.
    variables:
      protocol:
        enum:
          - http
          - https
        default: https

info:
  version: "1.0.0"
  title: API Recambios Opencart
  description:  |-
    API Recambios Opencart [https://telepieza.com/recambios/](https://telepieza.com/recambios/).
  contact: 
    email: telepieza@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

tags:
- name: customer_activity
  description: Manage customer_activity.
  externalDocs:
      description: Find out more about our store
      url: 'https://telepieza.com/recambios'

paths:
  /api/customer_activity/read:
    get:
      tags:
      - customer_activity
      summary: Get All categories
      operationId: GetAll
      parameters:
      - name: token
        in: header
        required: true
        style: simple
        schema:
          items:
              $ref: '#/components/schemas/Token'

      - name: limit
        in: query
        description: How many rows to return at one time (max 100)
        required: false
        explode: true
        schema:
          type: integer
          format: int64
          example: 20
      - name: offset
        in: query
        description: Gives the rows from the given position+1
        required: false
        explode: true
        schema:
          type: integer
          format: int64
          example: 1
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/GetAll'
        '403':
          $ref: '#/components/responses/ExpiredToken'
        '404':
           $ref: '#/components/responses/InvalidStatus'
        '500':
          $ref: '#/components/responses/ErrorInDataBase'
          
      security:
        - bearerAuth: [] 
          
  /api/customer_activity/read/{customer_activity_id}:
    get:
      tags:
        - customer_activity
      summary: Get One customer_activity by ID
      operationId: GetOne
      parameters:
      - name: token
        in: header
        required: true
        style: simple
        schema:
          items:
              $ref: '#/components/schemas/Token'

      - name: customer_activity_id
        in: path
        description: ID of customer_activity to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOne'
        '400':
          $ref: '#/components/responses/InvalidID'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ExpiredToken'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/ErrorInDataBase'
      security:
        - bearerAuth: [] 
      deprecated: false  
  /api/customer_activity/new:
    post:
      tags:
        - customer_activity
      summary: Add a new customer_activity
      description: Register a new customer_activity.
      operationId: Create
      parameters:
      - name: token
        in: header
        required: true
        style: simple
        schema:
          items:
              $ref: '#/components/schemas/Token'
              
      responses:
        '201':
            $ref: '#/components/responses/CreateID'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ExpiredToken'
        '404':
           $ref: '#/components/responses/NotCreate'
        '500':
           $ref: '#/components/responses/ErrorInDataBase'
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer_activity'
        required: true
         
      security:
        - bearerAuth: [] 
      deprecated: false  
  /api/customer_activity/update/{customer_activity_id}:
    post:
      tags:
        - customer_activity
      summary: Update an existing customer_activity
      description: Update an existing customer_activity by customer_activity_id.
      operationId: Update
      parameters:
      - name: token
        in: header
        required: true
        style: simple
        schema:
          items:
              $ref: '#/components/schemas/Token'

      - name: customer_activity_id
        in: path
        description: ID of customer_activity to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          $ref: '#/components/responses/Successful'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ExpiredToken'
        '404':
          $ref: '#/components/responses/NotUpdate'
        '500':
           $ref: '#/components/responses/ErrorInDataBase'
      requestBody:
        description: Update an existent customer_activity in the table
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/customer_activity'
      security:
        - bearerAuth: [] 
      deprecated: false  

  /api/customer_activity/delete/{customer_activity_id}:
    post:
      tags:
        - customer_activity
      summary: Delete customer_activity
      description: Delete a customer_activity.
      operationId: Delete customer_activity
      parameters:
      - name: token
        in: header
        required: true
        style: simple
        schema:
          items:
              $ref: '#/components/schemas/Token'

      - name: customer_activity_id
        in: path
        description: customer_activity_id of customer_activity to return
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '202':
          $ref: '#/components/responses/Successful'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ExpiredToken'
        '404':
          $ref: '#/components/responses/InvalidID'
        '500':
          $ref: '#/components/responses/ErrorInDataBase'
          
      security:
        - bearerAuth: [] 
      deprecated: false  
 
components:

  schemas:
  
    GetAll:
      title: GetHelp
      properties:
        status: 
          type: integer
          format: int32
          example : 200
        pagination:
          $ref: '#/components/schemas/Pagination'
        customer_activity:
          type: array
          xml:
            wrapped: true
          items:
             $ref: '#/components/schemas/customer_activity'
    
    GetOne:
      title: GetOne
      properties:
        status:
          type: integer
          format: int32
          example: 200
        customer_activity:
          $ref: '#/components/schemas/customer_activity'
          
    customer_activity:
       title: customer_activity
       type: object
       properties:
        customer_activity_id:
          type: integer
          format: int64
          example: 9
        customer_id:
          type: integer
          format: int64
          example: 1
        key:
          type: string
          example: Telepieza
        data:
          type: string
          example: Empresa Telepieza
        ip:
          type: string
          example: "210.234.120.20"
        date_added: 
          type : string
          format: date-time
          example: "2023-12-01 12:42:14"
        
       required:
         - customer_activity_id
         - customer_id
         
       example:
          customer_activity_id: 3
          customer_id: 4
          key: 930390_Telepieza
          data: Empresa Recambios Telepieza
          ip: "230.123.456.23"
          date_added: "2023-12-07 12:42:14"
 
    Pagination:
      title: Pagination
      type: object
      properties:
        currentPage:
          type: integer
          format: int64
          example: 1
        limit: 
          type: integer
          format: int32
          example: 20
        offset: 
          type: integer
          format: int32
          example: 0
        countRows:
          type: integer
          format: int64
          example: 27
        totalLimit: 
          type: integer
          format: int64
          example: 1
      required:
          - currentPage
          - limit
          - offset
          - countRows
          - totalLimit
      example:
        currentPage: 1
        limit: 20
        offset: 0
        countRows: 27
        totalLimit: 1
  
    Token:
      properties:
        token_type:
          type: string
          example: Bearer
        access_token:
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ945rtyRTWTQYW
      required:
        - token_type
        - access_token
      example:
        token_type: Bearer
        access_token: '{{jwt}}'
          
    Status_200:
      type: object
      properties:
        status:
          type: integer
          format: int32
        info:
          type: string
      required:
        - code
        - message
      example:
        status: 200
        info: successful operation

    Status_201:
      type: object
      properties:
        status:
          type: integer
          format: int32
        info:
          type: string
      required:
        - code
        - message
      example:
        status: 201
        info: The data has been created in the database with ID

    Status_400:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
      required:
        - code
        - message
      example:
        status: 400
        error: Invalid ID supplied

    Status_401:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
      required:
        - code
        - message
      example:
        status: 401
        error:  Access token is missing or invalid

    Status_403:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
      required:
        - code
        - message
      example:
        status: 403
        error:  Token invalid or Token required or Expired Token

    Status_404:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
      required:
        - code
        - message
      example:
        status: 404
        error:  Information not found
  
    Status_500:
      type: object
      properties:
        status:
          type: integer
          format: int32
        error:
          type: string
      required:
        - code
        - message
      example:
        status: 500
        error: Problems connecting to the database

  responses:
  
    Successful:
      description: successful operation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_200'
  
    NotFound:
      description: Information not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_404'
    
    CreateID:
      description: The data has been created in the database with ID
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_201'

    NotCreate:
      description: There has been an error creating
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_404'
            
    NotUpdate:
      description: There has been an error updating
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_404'
            
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_401'

    ExpiredToken:
      description: Token invalid or Token required or Expired Token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_403'
    
    InvalidID:
      description: Invalid ID supplied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_400'        
     
    InvalidStatus:
      description: Invalid status
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_404'           

    ErrorInDataBase:
      description: Problems connecting to the database
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Status_500' 
 
  securitySchemes:
    bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT